tmux config tweaks
Attempts to prevent random keystrokes from appearing on a fresh tmux
session. The ultimate culprit seems to have been `set escape-time 0`
but I've made various other tweaks as well to tmux and my `tn` launcher:

* Disable the tmux plugin manager
* Move more shell-focused config out of `tmux.conf` into `config.sh`
* Move named-session configuration into a `sessions/` subdirectory

Annoyingly, the new session doesn't seem to take all of the session
settings right away, requiring a reload of the config via Prefix+r.

diff --git a/bin/tn b/bin/tn
--- a/bin/tn
+++ b/bin/tn
@@ -8,10 +8,11 @@ set -e
 #fi
 
 NAME=${1:-default}
-MUXER=$(which tmux screen 2>/dev/null | head -n 1)
+CHOICES="tmux screen"
+MUXER=$(which $CHOICES 2>/dev/null | head -n 1)
 
 if [ -z "$MUXER" ] ; then
-    echo "Neither tmux nor screen are installed" 1>&2
+    echo "No muxer installed, couldn't find any of: $CHOICES" 1>&2
     exit 1
 fi
 if [ $# -gt 1 ] ; then
@@ -28,16 +29,17 @@ if [ -z "$SSH_AUTH_SOCK" ] && which ssh-agent >/dev/null 2>&1 ; then
 fi
 
 case "$MUXER" in
-    *tmux*)
+    */tmux*)
+        SESS_PREFIX="$XDG_CONFIG_HOME/tmux/sessions/$NAME"
         $AGENT "$MUXER" start-server
         if ! "$MUXER" has-session -t "$NAME" >/dev/null 2>&1 ; then
             # Session didn't exist, create it now
             cd ~
             "$MUXER" new-session -d -s "$NAME" -n "$NAME"
-            if [ -f "$XDG_CONFIG_HOME/tmux/$NAME.conf" ] ; then
-                "$MUXER" source-file -t "$NAME" "$XDG_CONFIG_HOME/tmux/$NAME.conf"
-            elif [ -x "$XDG_CONFIG_HOME/tmux/$NAME.sh" ] ; then
-                "$XDG_CONFIG_HOME/tmux/$NAME.sh"
+            if [ -f "$SESS_PREFIX.conf" ] ; then
+                "$MUXER" source-file -t "$NAME" "$SESS_PREFIX.conf"
+            elif [ -x "$SESS_PREFIX.sh" ] ; then
+                "$MUXER" run-shell -t "$NAME" "$SESS_PREFIX.sh"
             fi
         fi
         if [ -z "$TMUX" ] ; then
@@ -47,7 +49,8 @@ case "$MUXER" in
             "$MUXER" switch-client -t "$NAME"
         fi
         ;;
-    *screen*)
+    */screen*)
+        SESS_PREFIX="$XDG_CONFIG_HOME/screen/sessions/$NAME"
         # Protect against nested sessions
         if [ -n "$STY" ] ; then
             echo "You're already in a session ($STY)" 1>&2
@@ -57,8 +60,8 @@ case "$MUXER" in
             # Session didn't exist, create it now
             cd ~
             $AGENT "$MUXER" -S "$NAME" -d -m
-            if [ -f "$XDG_CONFIG_HOME/screen/$NAME.screenrc" ] ; then
-                "$MUXER" -S "$NAME" -X source "$XDG_CONFIG_HOME/screen/$NAME.screenrc"
+            if [ -f "$SESS_PREFIX.screenrc" ] ; then
+                "$MUXER" -S "$NAME" -X source "$SESS_PREFIX.screenrc"
             fi
         fi
         "$MUXER" -S "$NAME" -x -RR
