wstest: alternate home, don't test ASAN
Use `alternate-home.sh` when running the test suite, to fully rule out
any pollution from my dot files which could be tainting the test
results.

Check if Wireshark was compiled using ASAN, and skip testing entirely if
so. The ASAN output breaks the majority of test cases. This still lets
me use `wstest` as a short wrapper for rebuilding Wireshark.

diff --git a/bin/wsdev/wstest b/bin/wsdev/wstest
--- a/bin/wsdev/wstest
+++ b/bin/wsdev/wstest
@@ -76,6 +76,11 @@ fi
 
 m
 
-m --target test-programs
-unset WIRESHARK_LOG_LEVEL WIRESHARK_LOG_DOMAINS
-python3 -m pytest "$SRCPATH" "${MY_WSTEST_ARGS[@]}"
+if grep -q '^ENABLE_ASAN:BOOL=1$' "$BUILDPATH/CMakeCache.txt" ; then
+    echo "Skipping tests (ASAN output causes failures)"
+    exit 1
+else
+    m --target test-programs
+    unset WIRESHARK_LOG_LEVEL WIRESHARK_LOG_DOMAINS
+    "$HOME/bin/alternate-home.sh" python3 -m pytest "$SRCPATH" "${MY_WSTEST_ARGS[@]}"
+fi
